cspace/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from cspace import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '',
        TemplateView.as_view(template_name='cspace/index.html'),
        name='index'
    ),
    path('tag-index', views.tag_index, name='tag-index'),
    path('chem/<int:chem_id>/svg', views.draw_chemical, name='draw-chem'),
    path('chem-set/index', views.chemical_set_index, name='chemical-set-index'),
    path('chem-set/create', views.CreateChemicalSet.as_view(), name='create-chemical-set'),
    path('chem-set/<int:sid>', views.ChemicalSetDetail.as_view(), name='chemical-set'),
    path('facet/index', views.facet_index, name='facet-index'),
    path('facet/<int:fid>/data', views.get_facet_data, name='facet-data'),
    path('facet/<int:fid>', views.facet_page, name='facet-page'),
    path('facet/<int:fid>/search', views.sim_search, name='facet-search'),
    path('edit-smiles', views.edit_smiles, name='edit-smiles'),
    path('upload/sdf', views.UploadSDF.as_view(), name='upload-sdf'),
]

cspace/models.py
import json

from django.db import models

from rdkit.Chem.rdmolfiles import MolFromSmiles

from cspace.utils.memoize import memoize

SIM_MEASURES = (
    ('RDK/T', 'RDKit/Tanimoto'),
    ('GOBI/T', 'Gobi-Poppinger/Tanimoto'),
)

EMBEDDINGS = (
    ('3/RDK/MDS', '3/RDKit/Multidimensional Scaling'),
    ('3/RDK/NM-MDS', '3/RDKit/Non-Metric Multidimensional Scaling'),
    ('3/RDK/SMACOF', '3/RDKit/SMACOF MDS'),
    ('3/RDK/NM-SMACOF', '3/RDKit/Non-Metric SMACOF MDS'),
    ('3/TSNE', '3/TSNE'),
    ('3/ISOMAP', '3/ISOMAP'),
)

class ChemicalTag(models.Model):
    name = models.TextField(unique=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return 'tag: %s (%d compounds)' % (self.name, self.chemical_set.count())

class ChemicalSet(models.Model):
    name = models.TextField(unique=True)
    description = models.TextField(default='')
    created = models.DateField(auto_now_add=True)
    tags = models.ManyToManyField(ChemicalTag)

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return 'chem set: %s (%d compounds)' % (self.name, self.chemical_set.count())


class Chemical(models.Model):
    smiles = models.TextField(unique=True)
    chem_name = models.TextField()
    mol_weight = models.FloatField()
    tpsa = models.FloatField()
    pubchem_compound_cid = models.TextField()
    props_json = models.TextField()
    tags = models.ManyToManyField(ChemicalTag)
    sets = models.ManyToManyField(ChemicalSet)
    created = models.DateField(auto_now_add=True)

    @property
    @memoize
    def props(self):
        return json.loads(self.props_json)

    @property
    @memoize
    def mol(self):
        return MolFromSmiles(self.smiles)

    def get_mol(self):
        return MolFromSmiles(self.smiles)

class ChemicalSetFacet(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['embedding', 'sim_measure', 'chemical_set'],
                name='facet_identity'
            )
        ]

    name = models.TextField(unique=True)
    sim_measure = models.TextField(choices=SIM_MEASURES)
    embedding = models.TextField(choices=EMBEDDINGS)
    created = models.DateField(auto_now_add=True)
    chemical_set = models.ForeignKey(ChemicalSet, on_delete=models.CASCADE)
    dist_json = models.TextField()
    chem_ids_json = models.TextField()

class EmbeddedChemical(models.Model):
    chemical = models.ForeignKey(Chemical, on_delete=models.CASCADE)
    facet = models.ForeignKey(ChemicalSetFacet, on_delete=models.CASCADE)
    position = models.TextField()

class ComputeFacetJob(models.Model):
    chemical_set = models.ForeignKey(ChemicalSet, on_delete=models.CASCADE)
    sim_measure = models.TextField(choices=SIM_MEASURES)
    embedding = models.TextField(choices=EMBEDDINGS)
    facet = models.ForeignKey(
        ChemicalSetFacet,
        on_delete=models.CASCADE,
        null=True
    )
    status = models.IntegerField(choices=(
        (-1, 'Failed'),
        (0, 'Pending'),
        (1, 'Running'),
        (2, 'Done'),
    ), default=0)

cspace/forms.py
from django import forms

from cspace.models import *

class UploadSDFForm(forms.Form):
    tag = forms.CharField(max_length=64)
    sdf_file = forms.FileField(label='SDF File')

class CreateChemicalSetForm(forms.Form):
    name = forms.CharField(max_length=256)
    description = forms.CharField(widget=forms.Textarea)
    tags = forms.ModelMultipleChoiceField(
        queryset=ChemicalTag.objects.all(),
        required=True,
        widget=forms.CheckboxSelectMultiple
    )
    
class CreateFacetJobForm(forms.Form):
    chemical_set = forms.ModelChoiceField(
        queryset=ChemicalSet.objects.all(),
        widget=forms.HiddenInput
    )
    sim_measure = forms.ChoiceField(
            choices=SIM_MEASURES,
            label='Similarity Measure')
    embedding = forms.ChoiceField(choices=EMBEDDINGS)

    def clean(self):
        cleaned_data = super().clean()

        facet_query = ComputeFacetJob.objects.filter(
                chemical_set=cleaned_data['chemical_set'],
                sim_measure=cleaned_data['sim_measure'],
                embedding=cleaned_data['embedding']
            ).exclude(
                status=-1
            )

        if facet_query.count():
            raise forms.ValidationError('Identical job exists')

cspace/views.py
import json
import tempfile
import heapq

from django.db import transaction
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from rdkit import Chem
from rdkit.Chem.rdmolfiles import SDMolSupplier
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.rdmolfiles import MolToMolBlock, MolFromSmiles

from cspace.forms import UploadSDFForm, CreateChemicalSetForm, \
        CreateFacetJobForm
from cspace.utils import MethodSplitView, load_mol, get_distance_func, \
        big_qs_iterator, DuckChem
from cspace.models import *

def tag_index(request):
    tags = ChemicalTag.objects.all()

    return render(request, 'cspace/tag-index.html', {
        'tags': tags
    })

def chemical_set_index(request):
    sets = ChemicalSet.objects.all()

    return render(request, 'cspace/chemical-set-index.html', {
        'sets': sets
    })

def facet_index(request):
    facets = ChemicalSetFacet.objects.all()

    return render(request, 'cspace/facet-index.html', {
        'facets': facets
    })

class ChemicalSetDetail(MethodSplitView):
    def GET(self, request, sid):
        chem_set = get_object_or_404(ChemicalSet, pk=sid)
        create_facet_form = CreateFacetJobForm(
            initial={'chemical_set': chem_set}
        )

        return render(request, 'cspace/chemical-set-details.html', {
            'chem_set': chem_set,
            'create_facet_form': create_facet_form,
            'jobs': chem_set.computefacetjob_set.filter(status__lt=2)
        })

    def POST(self, request, sid):
        chem_set = get_object_or_404(ChemicalSet, pk=sid)
        create_facet_form = CreateFacetJobForm(request.POST)

        if create_facet_form.is_valid():
            job = ComputeFacetJob.objects.create(
                chemical_set=create_facet_form.cleaned_data['chemical_set'],
                sim_measure=create_facet_form.cleaned_data['sim_measure'],
                embedding=create_facet_form.cleaned_data['embedding'],
            )

            return HttpResponseRedirect(reverse('chemical-set', args=(sid,)))
        else:
            return render(request, 'cspace/chemical-set-details.html', {
                'chem_set': chem_set,
                'create_facet_form': create_facet_form,
                'jobs': chem_set.computefacetjob_set.filter(status__lt=2)
            })

def get_facet_data(request, fid):
    facet = get_object_or_404(ChemicalSetFacet, id=fid)

    points = []
    all_tags = set(facet.chemical_set.tags.all())
    max_dist_from_origin = 0

    echems = (EmbeddedChemical.objects
        .filter(facet=facet)
        .select_related('chemical'))

    for echem in echems:
        tags = all_tags & set(echem.chemical.tags.all())
        chem = echem.chemical
        position = json.loads(echem.position)

        dist_from_origin = sum([c*c for c in position])
        max_dist_from_origin = max(dist_from_origin, max_dist_from_origin)

        points.append({
            'name': chem.chem_name,
            'chem_id': chem.pk,
            'mol_weight': chem.mol_weight,
            'tpsa': chem.tpsa,
            'smiles': chem.smiles,
            'pos': position,
            'tags': [tag.name for tag in tags],
            'pubchem_cid': chem.props.get('PUBCHEM_COMPOUND_CID', None),
            'formula': chem.props.get('PUBCHEM_MOLECULAR_FORMULA', None),
            'svg_url': reverse('draw-chem', args=(chem.pk,))
        })

    return JsonResponse({
        'facet': {
            'id': facet.pk,
            'name': facet.name,
            'simMeasure': facet.sim_measure,
            'embedding': facet.embedding,
            'maxDistFromOrigin': max_dist_from_origin ** 0.5,
            'tags': sorted([tag.name for tag in all_tags])
        },
        'points': points,
    })

def draw_chemical(request, chem_id):
    chem = get_object_or_404(Chemical, id=chem_id)
    mol = chem.get_mol()
    mc = Chem.Mol(mol.ToBinary())

    try:
        Chem.Kekulize(mc)
    except:
        mc = Chem.Mol(mol.ToBinary())

    if not mc.GetNumConformers():
        Chem.rdDepictor.Compute2DCoords(mc)

    drawer = rdMolDraw2D.MolDraw2DSVG(300,200)
    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText().replace('svg:','')

    return JsonResponse({'data' : svg})

def facet_page(request, fid):
    facet = get_object_or_404(ChemicalSetFacet, id=fid)

    return render(request, 'cspace/space-viewer.html', {
        'facet_id': facet.pk
    })

class CreateChemicalSet(MethodSplitView):
    def GET(self, request):
        return render(request, 'cspace/create-chemical-set.html', {
            'form': CreateChemicalSetForm()
        })

    @transaction.atomic
    def POST(self, request):
        form = CreateChemicalSetForm(request.POST)

        if form.is_valid():
            tags = form.cleaned_data['tags']

            chem_set = ChemicalSet.objects.create(
                name=form.cleaned_data['name'],
                description=form.cleaned_data['description']
            )
            chem_set.save()

            chems = Chemical.objects.filter(tags__in=tags)
            chem_set.chemical_set.set(chems)
            chem_set.tags.set(tags)

            return HttpResponseRedirect(reverse('chemical-set-index'))


class UploadSDF(MethodSplitView):
    def GET(self, request):
        return render(request, 'cspace/upload-sdf.html', {
            'form': UploadSDFForm()
        })

    @transaction.atomic
    def POST(self, request):
        form = UploadSDFForm(request.POST, request.FILES)

        if form.is_valid():
            upload = request.FILES['sdf_file']
            tf = tempfile.NamedTemporaryFile()
            for chunk in upload.chunks():
                tf.write(chunk)

            tf.flush()
            tf.seek(0)
            molecules = SDMolSupplier(tf.name)

            tag, created = ChemicalTag.objects.get_or_create(
                name=form.cleaned_data['tag'])

            loaded = 0
            skipped = 0
            for mol in molecules:
                result = load_mol(mol, tag)

                if result == -1:
                    skipped += 1
                else:
                    loaded += 1

            return HttpResponseRedirect(reverse('tag-index'))

        else:
            return render(request, 'cspace/upload-sdf.html', {
                'form': form
            })

def edit_smiles(request):
    smiles = request.GET.get('SMILES', '')
    mol = MolFromSmiles(smiles)

    return render(request, 'cspace/chemical-editor.html', {
        'molblock': MolToMolBlock(mol)
    })

def sim_search(request, fid):
    facet = get_object_or_404(ChemicalSetFacet, pk=fid)
    chem_set = facet.chemical_set

    smiles = request.GET.get('SMILES', None)
    if not smiles:
        return JsonResponse({
            'status': 'FAILED'
        }, status=400)

    make_representation, distf = get_distance_func(facet.sim_measure)
    qrep = make_representation(DuckChem(smiles))

    sim_heap = []

    i = 0
    for chem in big_qs_iterator(chem_set.chemical_set.all(), batch_size=200):
        rep = make_representation(chem)
        sim = 1.0 - distf(qrep, rep)
        if i < 10:
            i += 1
            heapq.heappush(sim_heap, (sim, chem.pk, chem))
        else:
            heapq.heappushpop(sim_heap, (sim, chem.pk, chem))

    sim_heap.sort(reverse=True)

    return JsonResponse({
        'qrep': qrep.ToBase64(),
        'query': smiles,
        'status': 'OK',
        'results': dict(((pk, sim) for sim, pk, _ in sim_heap)),
    })

cspace/templates/cspace/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}UNNAMED PAGE{% endblock %} - C-Space</title>
    <meta name="author" content="Ryan 'Lanny' Jenkins">
    <meta name="description" content="Visualize spaces of embedded chemicals.">
    {% block css_main %}
      <link rel="stylesheet" href="{% static "css/stylesheet.css" %}" type="text/css">
    {% endblock %}
    {% block head_extra %}{% endblock %}
  </head>
  <body>
    {% block content %}
      <div class="header">
        <a href="{% url 'index' %}">
          <h1>C-Space</h1>
        </a>
        <div class="nav">
          <a href="{% url 'chemical-set-index' %}">View Chemical Sets</a>
          <a href="{% url 'create-chemical-set' %}">Create New Chemical Set</a>
          <a href="{% url 'upload-sdf' %}">Upload Chemicals</a>
        </div>
      </div>

      <div class="page-content-container">
        {% block page_content %}{% endblock %}
      </div>
    {% endblock %}
  </body>
</html>

cspace/templates/cspace/chemical-editor.html
{% extends "cspace/base.html" %}

{% load static %}

{% block title %}Chem Editor{% endblock %}

{% block css_main %}
<link
  rel="stylesheet"
  href="{% static "css/vendor/kekule.css" %}"
  type="text/css"
>
<style>
  body {
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    height: 100vh;
  }

  #done-button {
    width: 100%;
    color: white;
    background-color: #5a5aff;
    flex: 1;
    font-size: 18px;
    cursor: pointer;
  }

  #done-button:hover {
    background-color: #5050e2;
  }
</style>
{% endblock %}

{% block content %}

<script
  type="text/javascript"
  src="{% static 'js/vendor/kekule.min.js' %}"
>
</script>

<div
  id="chemComposer"
  style="width:800px;height:600px"
  data-widget="Kekule.Editor.Composer">
</div>

<button id="done-button">
  DONE
</button>

<script>
  var MOLBLOCK = '{{ molblock|escapejs }}' 
  var chemComposer;

  function init() {
    var mol = Kekule.IO.loadFormatData(MOLBLOCK, Kekule.IO.DataFormat.MOL);
    chemComposer = Kekule.Widget.getWidgetById('chemComposer');
    chemComposer
      .setAutoResizeConstraints({width: 1, height: 0.9})
      .setEnableDimensionTransform(true)
      .setAutoSetMinDimension(true)
      .setChemObj(mol);

    document.getElementById('done-button')
      .addEventListener('click', function() {
        var mol = chemComposer.exportObjs(Kekule.Molecule)[0];
        var smiles = Kekule.IO.saveFormatData(mol, 'smi');
        window.opener.postMessage({
          type: 'EDITING_COMPLETE',
          SMILES: smiles
        }, '*');
      })
  }
  Kekule.X.domReady(init);

  // Workaround for Kekule screwing this up somehow
  document.removeEventListener('DOMContentLoaded', Kekule.X.DomReady.initReady)
  document.addEventListener('DOMContentLoaded', function(){
    Kekule.X.DomReady._execFuncs()
  })


</script>
{% endblock %}

cspace/templates/cspace/chemical-set-details.html
{% extends "cspace/base.html" %}

{% block title %}Chemical Set: {{ chem_set.name }}{% endblock %}

{% block page_content %}
  <h2>Chemical Set: {{ chem_set.name }}</h2>

  <p>
    {{ chem_set.description }}
  </p>

  {% include "cspace/facet-table.html" with include_chem_set=False facets=chem_set.chemicalsetfacet_set.all %}

  <form action="{% url 'chemical-set' chem_set.pk %}" method="POST">
    <h3>Create New Facet</h3>
    {% csrf_token %}
    <table class="form-table">
      {{ create_facet_form.as_table }}
    </table>
    <input type="submit" value="Create" />
  </form>

  <table class="full-table">
    <thead>
      <tr>
        <th class="spanning-row" colspan="3">
          Incomplete Jobs
        </th>
      <tr>
        <th>Similarity Measure</th>
        <th>Embedding</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for job in jobs %}
        <tr>
          <td>{{ job.get_sim_measure_display }}</td>
          <td>{{ job.get_embedding_display }}</td>
          <td>{{ job.get_status_display }}</td>
        </tr>
      {% empty %}
        <tr>
          <td class="spanning-row" colspan="3">
            No Incomplete Jobs
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

cspace/templates/cspace/chemical-set-index.html
{% extends "cspace/base.html" %}

{% block title %}Chemical Sets{% endblock %}

{% block page_content %}
  <ol>
    {% for set in sets %}
      <li>
        <a href="{% url "chemical-set" set.pk %}">
          {{ set.name }} ({{ set.chemical_set.count }} compounds)
        </a>
      </li>
    {% endfor %}
  </ol>
{% endblock %}

cspace/templates/cspace/create-chemical-set.html
{% extends "cspace/base.html" %}

{% block title %}Create Chemical Set{% endblock %}

{% block page_content %}
  <h2>Create Chemical Set</h2>

  <form
    action="{% url 'create-chemical-set' %}"
    method="POST"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
  </form>
{% endblock %}

cspace/templates/cspace/facet-index.html
{% extends "cspace/base.html" %}

{% block title %}Chemical Set Facets{% endblock %}

{% block page_content %}
  <h2>All Chemical Set Facets</h2>

  {% include "cspace/facet-table.html" with include_chem_set=True facets=facets %}
{% endblock %}

cspace/templates/cspace/facet-table.html
<table class="full-table">
  <thead>
    <tr>
      <th 
        class="spanning-row"
        colspan="{% if include_chem_set %}5{% else %}4{% endif %}"
      >
        Chemical Set Facets
      </th>
    <tr>
      {% if include_chem_set %}
      <th>Chemical Set</th>
      {% endif %}
      <th>Similarity Measure</th>
      <th>Embedding Method</th>
      <th>Chemical Count</th>
      <th>View</th>
    </tr>
  </thead>

  <tbody>
    {% for facet in facets %}
      <tr>
        {% if include_chem_set %}
          <td>
            <a href="{% url "chemical-set" facet.chemical_set.pk %}">
              {{ facet.chemical_set.name }}
            </a>
          </td>
        {% endif %}
        <td>{{ facet.get_sim_measure_display }}</td>
        <td>{{ facet.get_embedding_display }}</td>
        <td>{{ facet.chemical_set.chemical_set.count }}</td>
        <td>
          <a href="{% url "facet-page" facet.pk %}">View</a>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td
          class="spanning-row"
          colspan="{% if include_chem_set %}5{% else %}4{% endif %}"
        >
          Empty facet set.
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

cspace/templates/cspace/index.html
{% extends "cspace/base.html" %}

{% load static %}

{% block title %}Home{% endblock %}

{% block page_content %}
  <p>
    CSpace is a tool for interactively visualizing chemical spaces in three dimensions with the goal of providing insight into the organization of large groups of chemicals and the relationship between chemical structure and effect.
  </p>
  <p>
    You can read more about the design of CSpace and some experiments <a href="{% static 'pdf/CSpace.pdf' %}">here</a>.
  </p>
{% endblock %}

cspace/templates/cspace/space-viewer.html
{% extends "cspace/base.html" %}
{% load static %}

{% block title %}Space Viewer{% endblock %}
{% block css_main %}{% endblock %}

{% block head_extra %}
<style>
  html, body {
    margin: 0;
    padding: 0;
  }

  canvas {
    outline: none;
  }
</style>
{% endblock %}


{% block content %}
  <div id="root"></div>
  <script>
    window.CSpace = {
      facetDataUrl: '{% url "facet-data" facet_id %}',
      searchUrl: '{% url "facet-search" facet_id %}',
      chemEditorUrl: '{% url "edit-smiles" %}',
    }
  </script>
  <script src="{% static "js/bundle.js" %}"></script>
{% endblock %}

cspace/templates/cspace/tag-index.html
{% extends "cspace/base.html" %}

{% block title %}Chemical Tags{% endblock %}

{% block page_content %}
  <ol>
    {% for tag in tags %}
      <li>
        <a href="#">
          {{ tag.name }} ({{ tag.chemical_set.count }} compounds)
        </a>
      </li>
    {% endfor %}
  </ol>
{% endblock %}

cspace/templates/cspace/upload-sdf.html
{% extends "cspace/base.html" %}

{% block title %}Upload Chemicals: SDF{% endblock %}

{% block page_content %}
  <h2>Upload Chemicals: SDF</h2>

  <form
    action="{% url 'upload-sdf' %}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload" />
  </form>
{% endblock %}